#markdown: kramdown

# For related posts
# lsi: true
# highlighter: pygments

permalink: pretty

safe: true

title: Tad Dallas
production_url: http://taddallas.github.io
description: Population ecology, community ecology, disease ecology, computational ecology,	ecological networks, complex systems, population dynamics, ecological forecasting
